# Generated by Django 4.2.11 on 2024-08-17 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_학교'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_score', models.IntegerField(default=0)),
                ('frontend_score', models.IntegerField(default=0)),
                ('design_score', models.IntegerField(default=0)),
                ('deploy_score', models.IntegerField(default=0)),
                ('ppt_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
