# Generated by Django 4.2.11 on 2024-11-08 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0011_conversation_matching_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pendingParticipants',
            field=models.ManyToManyField(blank=True, related_name='pending_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
