# Generated by Django 4.2.11 on 2024-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_conversation_pendingparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='contest_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
