# Generated by Django 4.2.11 on 2024-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_portfolio_conversation_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='conversation',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversations', to='conversations.portfolio'),
        ),
    ]
